add www support

diff --git a/bin/lux b/bin/lux
--- a/bin/lux
+++ b/bin/lux
@@ -19,7 +19,7 @@
 	readonly script_pid=$$
 	readonly script_author="qodeparty"
 	readonly script_id="lux"
-	readonly script_vers="0.2.0"
+	readonly script_vers="$(git describe --abbrev=0 --tags --exact-match)"
 	readonly script_prefix="LUX"
 	readonly script_rc_file=".luxrc"
 	readonly script_log_file="$script_id.log"
@@ -50,6 +50,7 @@
 	blambda="${blambda//#/}"
 	line="$(sed -n '16,16 p' $BASH_SOURCE)$nl"
 	diamond='\xE1\x9B\x9C'
+	delim='\x01'
 	pass="${green}\xE2\x9C\x93$x"
 	fail="${red}\xE2\x9C\x97$red2"
 	dots='\xE2\x80\xA6'
@@ -161,8 +162,11 @@
 		local data b w g p y s t n;
 		b=$blue;w=$wz;g=$grey2;p=$cyan;y=$orange;
 		s=$sp;t=$tab;n=$nl;
+		lux_mods
 		data="$(cat <<-EOF
 			$line
+			${s}${yellow}$script_id $script_vers build:$(lux_build_version 'build')
+
 			${s}${b}LUX_ID    = ${w}$LUX_ID
 			${s}${b}LUX_RC    = ${w}$LUX_RC
 			${s}${b}LUX_HOME  = ${w}${LUX_HOME//$THIS_ROOT/.}
@@ -183,6 +187,7 @@
 			${s}${p}THIS_DIR  = ${w}$THIS_DIR
 			${s}${p}BIN_DIR   = ${w}$BIN_DIR	
 
+			${s}${b}LUX_WWW   = ${y}$LUX_WWW
 			${s}${b}LUX_MODS  = ${y}${LUX_MODS[*]}	
 			${x}
 			$line
@@ -231,6 +236,8 @@
 	LUX_CORE="$LUX_HOME/src/styl/lux"
 	LUX_VARS="$LUX_HOME/src/styl/vars"
 	LUX_UTIL="$LUX_HOME/src/styl/util"
+
+	LUX_WWW="$( cd $THIS_DIR && cd ../lux-www; pwd -P )"
 
 	LUX_MODS=
 
@@ -283,7 +290,16 @@
 #-------------------------------------------------------------------------------
 # Utils
 #-------------------------------------------------------------------------------
+	function lux_build_version(){
+		case $1 in
+			www) echo $(cd $LUX_WWW;git rev-list HEAD --count);;
+			build) echo $(git rev-list HEAD --count);;
+			*) echo $(git describe --abbrev=0 --tags --exact-match);;
+		esac
+	}
+
 	
+
 	function lux_mods(){
 		LUX_MODS=($(find "$LUX_CORE" -type d -printf '%P\n' ))
 	}
@@ -293,7 +309,7 @@
 		src="$1"
 		data+=""
 		data="$(cat <<-EOF
-			/* $script_id v$script_vers | $script_lic (c)2018 $script_author | https://qodeparty.com/get/lux */
+			/* $script_id $script_vers | $script_lic (c)2018 $script_author | https://qodeparty.com/get/lux */
 		EOF
 		)";
 		printf '%s\n%s' "$data" "$(cat $src)" > $src
@@ -329,8 +345,25 @@
 
 
 	function lux_copy_res(){
+		info "Copying build & dist to res..."
 		mkdir -p "$LUX_RES"
 		[ -d "$LUX_BUILD" ] && cp $LUX_BUILD/*.css $LUX_RES || error "Missing build directory"
+		[ -d "$LUX_DIST"  ] && cp $LUX_DIST/*.css  $LUX_RES || error "Missing dist directory"
+	}
+
+
+	function lux_copy_www(){
+		local res ret build_id
+		info "Pushing generated files to www..."
+		if [ -d "$LUX_WWW"  ]; then
+			mkdir -p $LUX_WWW/res/build
+			cp -r $LUX_RES $LUX_WWW/res
+			cp -r $LUX_HOME/www/test $LUX_WWW
+			build_id="$(lux_build_version 'build')"
+			www_id="$(lux_build_version 'www')"
+			res=$(cd $LUX_WWW; git add -A .;git commit -m "build $build_id.$www_id"; git push origin; ); ret=$?
+			__print "$res"
+		fi
 	}
 
 
@@ -392,20 +425,18 @@
 				each)
 						silly "Rebuild each! ($thisb)"	 
 						lux_build_each
-						lux_copy_res
 						lux_build
 					;;
 				mod)  
 						silly "Rebuild mod! ($thisb)"	
 						lux_build_submod "$this"
-						lux_copy_res
 						lux_build
 					;;
 				*)    
 						silly "Woops!" 
 					;;
 			esac
-
+			lux_copy_res
 		fi
 	}
 
@@ -758,6 +789,7 @@
 					lux_listfile "htmllist" "test" "html"
 					;;
 				watch) lux_watch "$1"; shift;;
+				www) lux_copy_www;;
 				skip) break;;
 				--*) :;;
 				*) 
